### ISSUE TITLE
Update all just loads update menu again

### ISSUE THREAD

**Issue by JaCKoP619** [dw-0/kiauh#530] opened 2024-09-14 08:04 UTC
### Linux Distribution

Debian GNU/Linux 12 (raspberry)

### What happened

Tried to update all with the "a" option on the update menu, after kiauah's big update and switch to python 3.8 i think? It just loads the update menu again. I can update by separately choosing options but i always thought it was cool and convenient for it to use the "a" uption

### What did you expect to happen

For kiauah to update all installed (klipper related) packages that are viable for update

### How to reproduce

kiauah.sh -> 2 -> a 

### Additional information

i don't know it might be just me, but i liked this feature, it's an irrelevant bug but thought i'd bring this up here, sorry for the fuss.

**Comment by dw-0** [comment] 2024-09-14 16:22
duplicate of #526

**Closed by dw-0** 2024-09-14 16:22 UTC
