### ISSUE TITLE
Bad substitution -> Syntax error

### ISSUE THREAD

**Issue by catroc** [dw-0/kiauh#416] opened 2023-12-23 13:26 UTC
### Linux Distribution

Raspi 4 - bookworm

### What happened

Just want to start KIAUH ...

Gives me:
```
kiauh.sh: 16: Bad substitution
kiauh.sh: 14: -/scripts/backup.sh: Syntax error: "(" unexspected
```

### What did you expect to happen

Well ... starting KIAUH ^^

### How to reproduce

`sh ./kiauh/kiauh.sh`

### Additional information

I have installed it many times, tried an new image and a new sd card ...
Same problem when I install over git or copy it with winscp.

**Comment by pardovot** [comment] 2024-01-21 08:14
Same issue, after each time I restart the system or something this goes corrupted or something.

**Comment by itsj** [comment] 2024-01-27 15:14
Same issue for me. Installation via git.

**Comment by itsj** [comment] 2024-01-27 17:32
I've found the solution. You have to start the script from your home directory with
./kiauh/kiauh.sh
Before I start it within the kiauh directory.
Hope that help.

**Comment by dw-0** [comment] 2024-01-27 17:40
Im unable to reproduce the issue on Debian 12 Bookworm and Ubtunu 22.04.3 LTS:
![image](https://github.com/dw-0/kiauh/assets/31533186/78488640-0eaa-4fff-a83f-55ed42d9575a)
![image](https://github.com/dw-0/kiauh/assets/31533186/3358cd87-561a-4028-8c2b-92ad569428c5)

**Comment by dw-0** [comment] 2024-01-27 17:43
> I found a solution that works for me. You need to start the script from your home directory ./kiauh/kiauh.sh Before that I launched it in the Kiauh directory. Hope that helps.

That shouldn't make a difference.
`kiauh/kiauh.sh` does work as well as `cd kiauh` and then running `./kiauh.sh`

**Comment by itsj** [comment] 2024-01-27 17:48
Ahh. I try to start it with
sh kiauh.sh
So, my fault.

**Comment by dw-0** [comment] 2024-01-27 17:52
> ### How to reproduce
> `sh ./kiauh/kiauh.sh`

@catroc why do you execute it with sh instead of bash? That's your issue...

**Comment by itsj** [comment] 2024-01-27 17:55
It could be that @catroc tried following the same instructions as me.

**Comment by dw-0** [comment] 2024-01-27 18:01
Where do those instructions come from? @itsj

**Comment by pardovot** [comment] 2024-01-27 18:28
I probably did the same mistake, didn't came from any instructions, just the power of habit.

**Comment by itsj** [comment] 2024-01-27 18:37
Sorry, I can't retrace that anymore, too many videos. A German YouTuber.

**Comment by dw-0** [comment] 2024-01-27 18:40
Okay, no problem. I think we can close this issue then. It seems that everything boils down to executing the script in an incorrect way :)

**Closed by dw-0** 2024-01-27 18:40 UTC
Labels: question, can't reproduce

**Comment by itsj** [comment] 2024-01-27 18:42
Your right, now it works like a charm!
