### ISSUE TITLE
add Python & numpy installation to KIAUH

### ISSUE THREAD

**Issue by hitman01560** [dw-0/kiauh#384] opened 2023-09-25 20:22 UTC
### Is your feature request related to a problem? Please describe

easier method to get the ADXL functions right out of the box

### Describe the solution you'd like

adding a script for automatic installation of Python and numpy by choosing a number like other functions in KIAUH

sudo apt install python3-numpy python3-matplotlib libatlas-base-dev
~/klippy-env/bin/pip install -v numpy

**Comment by dw-0** [comment] 2023-10-31 09:52
duplicate of #103

**Closed by dw-0** 2023-10-31 09:52 UTC
Labels: feature request
