### ISSUE TITLE
[Feature Request] Add option to install Mooncord

### ISSUE THREAD

**Issue by dburr** [dw-0/kiauh#320] opened 2023-03-23 20:27 UTC
### Is your feature request related to a problem? Please describe

Discord is a popular chat platform. However, it is also a very popular way for people to add command & control services for various hardware/software, as the Discord API is well documented, free to use, and is supported by many third party libraries. In my case, I use a private Discord server as a place where I can control and view status of all of my various home automation devices, as well as my 3D printer.

### Describe the solution you'd like

[Mooncord](https://github.com/eliteSchwein/mooncord) is software that allows interfacing between Klipper/Moonraker and Discord.

### Describe alternatives you've considered

It is certainly possible to hand install Mooncord, however having it available in KIAUH would be extremely convenient.

### Additional information

none really

**Comment by dw-0** [comment] 2023-10-31 08:35
duplicate of #282

**Closed by dw-0** 2023-10-31 08:35 UTC
Labels: feature request
